import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { NextTopLoader } from "./common/NextTopLoader";
import { cn } from "@/lib/utils";
import styles from "@/styles.module.css";
import { geologica } from "@/src/utils/font";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cn(styles["bg-gradient-to-custom-services"])} ${cn(geologica.className, "font-sans")}`}>
        <Toaster position="top-right" />
        <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
